import { Badge } from '@/components/Badge';
import { TagDot } from '@/components/TagDot';
import type { EntityListItem } from '@/patterns/EntityList';

/** Sample rows for the list stories: a team shipping a spring launch. */
export const ROWS: EntityListItem[] = [
  {
    id: 'plan',
    group: 'Today',
    kind: 'document',
    title: 'Spring launch plan',
    secondary: 'Launch / Planning',
    time: '2m',
    unread: true,
    people: [{ name: 'Nina Park' }, { name: 'Omar Haddad' }],
    badges: <span className="inline-flex min-w-0 items-center gap-2 text-xs text-ink-muted"><TagDot fill="var(--color-blue)" size="sm" />Launch</span>,
  },
  {
    id: 'faq',
    group: 'Today',
    kind: 'task',
    title: 'Draft the pricing FAQ',
    secondary: 'Due Friday',
    time: '14m',
    unread: true,
    people: [{ name: 'Lena Novak' }],
    badges: <Badge size="sm">In progress</Badge>,
  },
  {
    id: 'contract',
    group: 'Today',
    kind: 'pdf',
    title: 'Venue contract.pdf',
    secondary: '2.4 MB, shared by Omar',
    time: '1h',
    people: [{ name: 'Omar Haddad' }],
  },
  {
    id: 'budget',
    group: 'Today',
    kind: 'spreadsheet',
    title: 'Launch budget',
    secondary: 'Finance',
    time: '3h',
    badges: <span className="inline-flex min-w-0 items-center gap-2 text-xs text-ink-muted"><TagDot fill="var(--color-green)" size="sm" />Finance</span>,
  },
  {
    id: 'sync',
    group: 'Yesterday',
    kind: 'call',
    title: 'Weekly launch sync',
    secondary: '32 min, 5 people',
    time: '4:30 PM',
    people: [{ name: 'Nina Park' }, { name: 'Omar Haddad' }, { name: 'Lena Novak' }, { name: 'Jonas Berg' }, { name: 'Priya Shah' }],
  },
  {
    id: 'assets',
    group: 'Yesterday',
    kind: 'folder',
    title: 'Launch assets',
    secondary: '14 items',
    time: '11:02 AM',
  },
  {
    id: 'hero',
    group: 'Yesterday',
    kind: 'image',
    title: 'hero-shot.png',
    secondary: '1920 × 1080',
    time: '9:40 AM',
    people: [{ name: 'Priya Shah' }],
  },
  {
    id: 'demo',
    group: 'Earlier',
    kind: 'video',
    title: 'Product demo.mp4',
    secondary: '4:12',
    time: 'Tue',
    badges: <Badge size="sm" className="border-transparent bg-violet-bg text-violet-ink">Final cut</Badge>,
  },
  {
    id: 'voiceover',
    group: 'Earlier',
    kind: 'audio',
    title: 'Voiceover take 3.m4a',
    secondary: '1:48',
    time: 'Mon',
  },
  {
    id: 'reminder',
    group: 'Earlier',
    kind: 'reminder',
    title: 'Send press kit to partners',
    secondary: 'Sep 24, 9:00 AM',
    time: 'Sep 14',
  },
  {
    id: 'notes',
    group: 'Earlier',
    kind: 'file',
    title: 'launch-checklist.txt',
    secondary: '3 KB',
    time: 'Sep 12',
  },
  {
    id: 'press',
    group: 'Earlier',
    kind: 'link',
    title: 'Press coverage tracker',
    secondary: 'news.example.com',
    time: 'Sep 10',
  },
];
